lzc-sdk-version: "0.1"
name: Cloudflared
package: dev.libr.cloudflared
version: 0.0.11
description: Cloudflare Tunnel 提供了一种安全的方式，可以将 Web 服务器安全地公开到互联网上，而无需打开防火墙端口和配置访问控制列表（ACL）。Cloudflare Tunnel 还确保请求在到达 Web 服务器之前通过 Cloudflare 路由，因此您可以确保攻击流量会被 Cloudflare 的 WAF 和无限制的 DDoS 缓解功能阻止，并在启用了这些功能的情况下通过 Access 进行身份验证。
homepage: https://cloudflare.com
author: libr
application:
  subdomain: cf
  background_task: true
  multi_instance: false
  routes:
    - /=http://cloudflared.dev.libr.cloudflared.lzcapp:14333/
services:
  cloudflared:
    network_mode: host
    mark: 2025.10.0
    image: registry.lazycat.cloud/u7842111934/wisdomsky/cloudflared-web:234275360357b9dc
    # image: registry.lazycat.cloud/u7842111934/wisdomsky/cloudflared-web:95952a939c6c4dff
    # image: registry.lazycat.cloud/u7842111934/wisdomsky/cloudflared-web:b4a89e2558118c2a # wisdomsky/cloudflared-web:2025.7.0
    binds:
      - /lzcapp/var/config:/config
      # - /lzcapp/var/hosts:/etc/hosts
    environment:
      - PROTOCOL=http2 # use protocol=http2 https://github.com/cloudflare/cloudflared/issues/1228#issuecomment-2586683258
      # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/tunnel-with-firewall/
      # - EDGE_BIND_ADDRESS=198.41.192.27
    restart: always
